package com.example.mercadolibretest.presentation.state

data class MLItemState(
    val id: String,
    val title : String,
    val condition: String,
    val thumbnail: String,
    val catalog_product_id: String,
    val listing_type_id: String,
    val permalink: String,
    val buying_mode: String,
    val site_id: String,
    val category_id: String,
    val domain_id: String,
    val currency_id: String,
    val price: Float,
    val original_price: Float = -1f,
    val sale_price: Float = -1f,
    val sold_quantity: Int,
    val available_quantity: Int,
    val accepts_mercadopago: Boolean,
    val tags: List<String>,
) {
}

fun MLItemState.getEmpty() = MLItemState(
    id = "",
    title = "",
    condition = "",
    thumbnail = "",
    catalog_product_id = "",
    listing_type_id = "",
    permalink = "",
    buying_mode = "",
    site_id = "",
    category_id = "",
    domain_id = "",
    currency_id = "",
    price = -1f,
    original_price = -1f,
    sale_price = -1f,
    sold_quantity = 0,
    available_quantity = 0,
    accepts_mercadopago = false,
    tags = listOf(),
)
